### ISSUE TITLE
Spell doesn't load in Windows

### ISSUE THREAD

**Issue by negm** [foobarmus/autocorrect#4]
I traced the issue to utils.py -> with closing(t.extractfile(tar_path)) as f:
it seems the tarfile library doesn't behave as intended on Windows. I extracted the file manually and changed the code to open it using os.open for now but I intended to make a pull request with a more general solution soon
Thanks for your effort

**Comment by foobarmus** [comment]
Hey, thanks for yours!

I didn't have access to a windows system when I was building that, so I'm
not surprised about the issue. Happy to incorporate your improvements if
they're neat and tidy

Cheers

Jonas

**Comment by Zederich** [comment]
I have changed the source code to work on windows. Because tar can be a little bit finicky, I switched to an LZMA zip file instead of the bzipped one and just used the standard ZipFile module. An advantage to this is that the file takes a little less space and is more cross-platform. I'll make a pull request for the updated version, but if you want to keep yours the way it is I can make a windows fork.

**Comment by Zederich** [comment]
Ok, cant' figure out the pull requests, but here's my code: [Gist](https://gist.github.com/Zederich/a3ec61816d5490b57679e1850074f142)
[words.zip](https://github.com/foobarmus/autocorrect/files/264887/words.zip)
This is the LZMA zip file.

**Comment by InTheZ** [comment]
Hi, I submitted a pull request to fix this issue. I found that a LZMA formatted file doesn't seem to work in a default install of windows.

**Comment by Odianosen25** [comment]
@CedricDonie Please how can I download ur updated code for Windows? I need to use this on a windows machine and being a newbie, con't figure how u fixed it.

Thanks

**Comment by Odianosen25** [comment]
@foobarmus many thanks for your work on this, but I kindly have a few questions:

1) It installs and functions fine on my RPi, but on my Windows, I get this error `Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from autocorrect import spell
  File "C:\Users\userEOdianosen\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autocorrect\__init__.py", line 16, in <module>
    from autocorrect.nlp_parser import NLP_COUNTS
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autocorrect\nlp_parser.py", line 26, in <module>
    NLP_WORDS, NLP_COUNTS = parse('big.txt')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\autocorrect\nlp_parser.py", line 20, in parse
    words = words_from_archive(lang_sample, include_dups=True)
TypeError: words_from_archive() got an unexpected keyword argument 'include_dups'`

Please any help will be greatly appreciated on how to solve this.

2) If I want to be able to update the words used in the module, which of the text file please should I input my words?

Regards
